spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart
    driver-class-name: org.postgresql.Driver
    username: user
    password: pass
  kafka:
    bootstrap-servers: localhost:9092
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_schema: public
    show-sql: true
  sql:
    init:
      mode: always

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

analyzer:
  hub-topic: telemetry.hubs.v1
  snapshots-topic: telemetry.snapshots.v1


logging:
  level:
    root: INFO
    ru.practicum.analyzer: DEBUG
    org.hibernate.SQL: TRACE
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction.interceptor: TRACE