spring:
  profiles:
    active: main-service
  datasource:
    url: jdbc:postgresql://localhost:5433/shopping_store
    driver-class-name: org.postgresql.Driver
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: store
    show-sql: true
  sql:
    init:
      mode: always
server:
  port: 0

springdoc:
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: INFO
    ru.practicum.yandex.shopping.store: DEBUG
    org.hibernate.SQL: TRACE
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction.interceptor: TRACE